title: Online Money Heist
email: onlinemoneyheist@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Make Money Online!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
analytics-id: UA-172670103-1


# Build settings
plugins:
  - jekyll-assets
  - kramdown
  - uglifier

source: src
destination: www
markdown: kramdown

cards:
  data: films         # yaml file in _data (without .yml)
  comments: false
  group_by:
    name: decade      # field in yaml to group by
    caption: decades  # name of category (ex: industries)
    fa-icon: tasks
           # valid: fas (solid), far (regular), fal (light), fab (brand)
  meta:               # use this section to display card info, in addition to 'group_by'
    - name: year
      caption: year
      fa-icon: money

    - name: url
      caption: www
      fa-icon: link
      


compress_html:
  ignore:
    envs: ["development"]
  clippings: []
  comments: all
  endings: []
  startings: []
  blanklines: false
  profile: false

assets:
  sources:
  - _assets/vendor
  digest: true
  compression: true
  gzip: false
  defaults:
    js: { integrity: false } # true on JEKYLL_ENV=production
    css: { integrity: false } # true on JEKYLL_ENV=production
    img: { integrity: false } # true on JEKYLL_ENV=production
  compress:
    css: false
    js: uglifier

include:
  - CNAME
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
